[virtualization] Remove redundant libc imports.
This removes compiler errors with the message below. The errors started
showing up when the unused-imports Rust warning was promoted to a build
failure.

    error: the item `libc` is imported redundantly
     --> ../../src/virtualization/tests/virtio_gpu_test_util/src/linuxfb.rs:8:5
      |
    8 |     libc,
      |     ^^^^ the item `libc` is already defined by prelude
      |
      = note: requested on the command line with `-D unused-imports`

Test: fx build (no behavior changes)
Change-Id: I3fd57466638a8b01bcb9246310b3e3be3fdf2797
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1006492
Commit-Queue: Victor Costan <costan@google.com>
Reviewed-by: Tim Kilbourn <tkilbourn@google.com>
Fuchsia-Auto-Submit: Victor Costan <costan@google.com>